language: "ko-KR"
reviews:  # 작동 정책
  profile: "chill"                 # 리뷰 스타일(친근함 정도)
  request_changes_workflow: false  # 리뷰에서 "Change requested" 플래그 달지 여부
  high_level_summary: true         # 요약 리뷰를 남길지 여부
  poem: false                      # (이스터에그) 시 형태 리뷰 금지
  review_status: true              # 리뷰 완료 상태 표시
  auto_review:
    enabled: true                  # PR 생성 시 자동 리뷰 활성화
    drafts: false                  # draft PR은 리뷰하지 않음
    base_branches:
        - main
        - dev
